In [1]:
import numpy as np

a = np.array([2,3,4,5,6,7])
print(a)
print(type(a))

[2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,0,0,0])

print(a + b)
print(a*b)
print(a-b)

[ 8 10 12  4  5  6]
[ 7 16 27  0  0  0]
[-6 -6 -6  4  5  6]


In [3]:
import numpy 

arr = numpy.array([2,3,4,5,6,7,8])

# squrt values in array. each item
print(numpy.sqrt(arr))

# sum of the array
print(numpy.sum(arr))

# average get in an array
print(numpy.mean(arr))

# max value in array
print(numpy.max(arr))

# min value in array
print(numpy.min(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131
 2.82842712]
35
5.0
8
2


In [8]:
arr_1 = np.array([[9,10,5],[4,12,20]])
print(arr_1)
print(arr_1.size)
print(arr_1.ndim)
print(arr_1.shape)

[[ 9 10  5]
 [ 4 12 20]]
6
2
(2, 3)


In [12]:
arr_1 = np.array([[[8,3,1],[5,9,8]],[[20,10,11],[4,12,20]]])
print(arr_1)
print(arr_1.size)
print(arr_1.ndim)
print(arr_1.shape)


[[[ 8  3  1]
  [ 5  9  8]]

 [[20 10 11]
  [ 4 12 20]]]
12
3
(2, 2, 3)


In [9]:
# Data types in numpy arrays(dtype)
import numpy as np

arr_1 = np.array([5,7,9,2])
print(arr_1.dtype)

# Changing one data type to float 
arr_1 = np.array([5,7,9,2,10,2.2])
print(arr_1.dtype)

## Changing one data type to boolean  
arr_1 = np.array([5,7,9,2,10,True])
print(arr_1.dtype)



int64
float64
int64


In [ ]:
# array indexing
import numpy as np

arr_1 = np.array([5,9,11,4])
print(arr_1[0])  # First element
print(arr_1[1])  # Second element

arr_2 = np.array([[5,9,11],[4,6,8]])
print(arr_2[1, 2])  

# Negative indexing
print(arr_2[-2,-2]) 

5
9
8
4


In [11]:
# Boolean indexing

arr_1 = np.array([10,20,30,40,50])
condition = arr_1 > 25
print(condition)

print(arr_1[condition])  #condition eke true wena values print wenawa

print(arr_1[arr_1 > 25])  #uda ek one line ekkin


[False False  True  True  True]
[30 40 50]
[30 40 50]


In [13]:
arr_1 = np.array([10,20,30,40,50])
print(arr_1[(arr_1 > 25) & (arr_1 < 45)]) 

# & and
# | or
# ~ not

[30 40]


In [ ]:
# Q1)

temp = np.array([
    [31,30,28],
    [29,29,32],
    [26,24,27],
    [31,34,35],
    [28,31,30]
])

daily_avg = np.mean(temp)
print(daily_avg)

result = temp[greater_than_avg]
print(result)

29.666666666666668
[31 30 32 31 34 35 31 30]


In [ ]:
# np.zeros
print(np.zeros((2,3)))
print(np.zeros(5))

# np.ones
print(np.ones((2,3)))
print(np.ones(5))

# np.full
print(np.full((2,3), 5))
print(np.full(5, 5))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1.]
[[5 5 5]
 [5 5 5]]
[5 5 5 5 5]


In [50]:
print(np.full((2,3),(1,2,3)))

[[1 2 3]
 [1 2 3]]


In [ ]:
# np.empty

print(np.empty((2,3)))

[[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]


In [ ]:
# pandas library

import pandas as pd

data = {'name':['Alice','Bob','charlie','David'],
        'age':[25,30,35,40]}

df = pd.DataFrame(data)
print(df)

print(df.loc[0,'name'])  # First row, name column

print(df.iloc[2, 1])  # row index ekai column index ekai use krl access krai

print(df.loc[2])

print(df.iloc[2])  

AttributeError: partially initialized module 'pandas' from 'C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\pandas\__init__.py' has no attribute 'core' (most likely due to a circular import)

In [ ]:
df = pd.DataFrame(data, index=["student_1", "student_2", "student_3", "student_4"])
print(df)






              name  age
student_1    Alice   25
student_2      Bob   30
student_3  charlie   35
student_4    David   40
name    charlie
age          35
Name: student_3, dtype: object
name    charlie
age          35
Name: student_3, dtype: object


In [19]:
# access 3rd using loc and iloc
import pandas as pd

print(df.loc["student_3"])  

# access 2nd using iloc
print(df.iloc[2])

NameError: name 'df' is not defined

In [ ]:
# access 2nd and 4th using loc

print(df.loc[["student_2", "student_4"]])


            name  age
student_2    Bob   30
student_4  David   40


In [ ]:
# accessing columns

age_column = df['age']
print(age_column)

name_column = df['name']
print(name_column)

student_1    25
student_2    30
student_3    35
student_4    40
Name: age, dtype: int64
student_1      Alice
student_2        Bob
student_3    charlie
student_4      David
Name: name, dtype: object


In [76]:
print(df.columns)  # Get all column names

print(list(df.columns))  # Convert column names to a list

Index(['name', 'age'], dtype='object')
['name', 'age']


In [79]:
print(df.size)
print(df.shape)  # Get the shape of the DataFrame (rows, columns)
print(len(df))

8
(4, 2)
4


In [81]:
print(df.values)  # Get the values of the DataFrame as a NumPy array
print(type(df.values))  # Check the type of the values

[['Alice' 25]
 ['Bob' 30]
 ['charlie' 35]
 ['David' 40]]
<class 'numpy.ndarray'>


In [ ]:
# sum and average of age column

print(df['age'].mean())
print(df['age'].sum())

32.5
130


In [87]:
# add new column

df['city'] = ['colombo', 'kandy', 'galle', 'matara']
df['salary'] = [50000, 60000, 70000, 80000]
print(df)

              name  age     city  salary
student_1    Alice   25  colombo   50000
student_2      Bob   30    kandy   60000
student_3  charlie   35    galle   70000
student_4    David   40   matara   80000


In [ ]:
# filtering rows based on a condition
filtered_df = df[df['age'] > 30]
print(filtered_df)
print(type(filtered_df))

              name  age    city  salary
student_3  charlie   35   galle   70000
student_4    David   40  matara   80000
<class 'pandas.core.frame.DataFrame'>


In [ ]:
filtered_df = df[(df['age'] > 28) & (df['salary'] < 65000)]
print(filtered_df)

          name  age   city  salary
student_2  Bob   30  kandy   60000


In [ ]:
# Q2)

# i)
data = {'student_id':[1001,1002,1003,1004,1005],
        'name':['Ayesha','Nimal','Tharindu','kasun','shashini'],
        'assignment_1':[78,65,88,50,80],
        'assignment_2':[85,70,90,40,75],
        'final_exam':[90,72,95,60,85]
        }
df = pd.DataFrame(data)
print(df)

# ii)
high_scorers = df[df['final_exam'] > 80]
print(high_scorers[['name', 'final_exam']])

# iii)
df['average_score'] = (df['assignment_1'] + df['assignment_2'] + df['final_exam']) / 3
print(df)

# iv)
df['heighest_avg'] = df['average_score'].max()
print(highest_avg)

# v)
print(df['assignment_1'].sum())



   student_id      name  assignment_1  assignment_2  final_exam
0        1001    Ayesha            78            85          90
1        1002     Nimal            65            70          72
2        1003  Tharindu            88            90          95
3        1004     kasun            50            40          60
4        1005  shashini            80            75          85
       name  final_exam
0    Ayesha          90
2  Tharindu          95
4  shashini          85
   student_id      name  assignment_1  assignment_2  final_exam  average_score
0        1001    Ayesha            78            85          90      84.333333
1        1002     Nimal            65            70          72      69.000000
2        1003  Tharindu            88            90          95      91.000000
3        1004     kasun            50            40          60      50.000000
4        1005  shashini            80            75          85      80.000000
91.0
361


In [ ]:
# csv file read in pandas

df = pd.read_csv('test.csv')
print(df)
print(type(df))

          Name  Age Occupation
0     John Doe   30   Engineer
1   Jane Smith   25    Teacher
2  Bob Johnson   40     Doctor
3  Alice Brown   35     Artist
<class 'pandas.core.frame.DataFrame'>


In [114]:
# json file read in pandas
df_json = pd.read_json('test.json')
print(df_json)
print(type(df_json))

       name  age  isStudent    hobbies
0  John Doe   30      False    reading
1  John Doe   30      False  gardening
2  John Doe   30      False   swimming
<class 'pandas.core.frame.DataFrame'>
